//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillResultsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public string Description { get; set; }
        public bool Hidden { get; set; }
        public string Type { get; set; }
    }
}
