//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillResultsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaCategoriesMaster
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string CategoryType { get; set; }
        public int AreaId { get; set; }
        public string AreaType { get; set; }
        public System.DateTime Created { get; set; }
        public string Type { get; set; }
    }
}
