//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillResultsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUser
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public string UserId { get; set; }
        public System.DateTime Created { get; set; }
        public int Admin { get; set; }
        public string AuthKey01 { get; set; }
        public string AuthKey02 { get; set; }
        public Nullable<System.DateTime> AuthKeyExpires { get; set; }
    }
}
