//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillResultsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEducation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int OrgId { get; set; }
        public Nullable<int> Institution { get; set; }
        public bool OtherInstitution { get; set; }
        public string OtherInstitutionDesc { get; set; }
        public int DegreeLevel { get; set; }
        public Nullable<int> DegreeType { get; set; }
        public Nullable<int> Major { get; set; }
        public bool OtherMajor { get; set; }
        public string OtherMajorDesc { get; set; }
        public Nullable<int> Minor { get; set; }
        public bool OtherMinor { get; set; }
        public string OtherMinorDesc { get; set; }
        public Nullable<int> Concentration { get; set; }
        public bool OtherConcentration { get; set; }
        public string OtherConcentrationDesc { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> ExpectedCompletionDate { get; set; }
        public bool Private { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
